/*
I created an SQL query and a Tableau dashboard to analyze the financial performance of the project. 
The dashboard was designed to help product managers track revenue dynamics and perform high-level analysis of the factors driving these changes.

Here are the metrics I calculated:
Monthly Recurring Revenue (MRR)
Paid Users
Average Revenue Per Paid User (ARPPU)
New Paid Users
New MRR
Churned Users
Churn Rate
Churned Revenue
Revenue Churn Rate
Expansion MRR
Contraction MRR
Customer Lifetime (LT)
Customer Lifetime Value (LTV)
This analysis provided valuable insights into user behavior, helping identify trends in revenue growth and churn, 
and enabling better strategic decisions for product management.
Link to Tableau 
https://public.tableau.com/views/ProjectRevenueMetricsMetrostyle_17315871041780/RevenueMetrics?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
*/


WITH monthly_data AS (
SELECT 
	DATE_TRUNC('month', gp.payment_date) AS month,
	gp.user_id,
	gp.revenue_amount_usd,
	gp.payment_date
FROM 
    project.games_payments AS gp),
/* 

Monthly Recurring Revenue (MRR) is the total revenue for a calendar month, 
but only if this revenue comes from sources that recur month to month.
*/
monthly_mrr AS (
SELECT 
    month,
    SUM(revenue_amount_usd) AS mrr
FROM 
    monthly_data
GROUP BY 
    month),
/*

Paid Users - the number of users who make payments.
*/
paid_users_count AS (
SELECT 
    month,
    COUNT(DISTINCT user_id) AS paid_users
FROM 
    monthly_data
WHERE 
    revenue_amount_usd > 0
GROUP BY 
    month),
/*

Average Revenue Per Paid User (ARPPU) is the average revenue per paying user.
It is calculated as ARPPU = Revenue / Paid Users.
 */
arppu AS (
SELECT 
    mrr_data.month,
    ROUND(mrr_data.mrr::DECIMAL / paid_data.paid_users, 2) AS arppu
FROM 
    monthly_mrr AS mrr_data
JOIN 
    paid_users_count AS paid_data ON mrr_data.month = paid_data.month),
/*

New Paid Users - the number of users who became paying during the respective time period.
 */
new_paid_users AS (
SELECT 
    DATE_TRUNC('month', first_pay_date) AS month,
    COUNT(user_id) AS new_paid_users
FROM (SELECT 
          user_id,
          MIN(payment_date) AS first_pay_date
      FROM 
          project.games_payments
      GROUP BY 
          user_id) AS first_payments
GROUP BY 
    DATE_TRUNC('month', first_pay_date)),
/* 

New MRR is the MRR generated by users who became paying customers in the corresponding month
 */
new_mrr AS (
SELECT 
    month,
    SUM(revenue_amount_usd) AS new_mrr
FROM 
    monthly_data AS gp
JOIN (SELECT 
          user_id,
          MIN(payment_date) AS first_pay_date
      FROM 
          project.games_payments
      GROUP BY 
            user_id) AS fp ON gp.user_id = fp.user_id 
      AND DATE_TRUNC('month', gp.payment_date) = DATE_TRUNC('month', fp.first_pay_date)
GROUP BY 
    month),
/*

Churned Users - the number of users who stopped paying during the corresponding period of time.
*/
churned_users AS (
SELECT 
     payment_month AS churned_month,
     COUNT(user_id) AS churned_user_count
FROM (SELECT 
          user_id,
          MAX(DATE_TRUNC('month', payment_date)) AS payment_month
      FROM 
          monthly_data
      GROUP BY 
          user_id) AS last_payments
GROUP BY 
      payment_month),
/*

Churn Rate is the ratio of Churned Users in the target time period to Paid Users in the previous period.
For example, Churn Rate (June) = Churned Users (June) / Paid Users (May).
 */
churn_rate AS (
SELECT 
     churned_month,
     churned_user_count,
     LAG(paid_users_count.paid_users) OVER (ORDER BY churned_month) AS prev_month_paid_users,
     CASE 
         WHEN LAG(paid_users_count.paid_users) OVER (ORDER BY churned_month) > 0 
         THEN ROUND(churned_user_count::DECIMAL / LAG(paid_users_count.paid_users) OVER (ORDER BY churned_month), 2)
         ELSE NULL
     END AS churn_rate
FROM 
     churned_users
JOIN 
     paid_users_count ON churned_month = paid_users_count.month),
/*

Churned revenue is the total revenue from the previous period generated by all users who stopped paying.
*/
churned_revenue AS (
SELECT 
     month,
     SUM(revenue_amount_usd) AS churned_revenue
FROM 
     monthly_data AS gp
JOIN (SELECT 
          user_id,
          MAX(payment_date) AS last_pay_date
      FROM 
          project.games_payments
      GROUP BY 
          user_id) AS lp ON gp.user_id = lp.user_id 
      AND DATE_TRUNC('month', gp.payment_date) = DATE_TRUNC('month', lp.last_pay_date)
GROUP BY 
     month),
/*

Revenue Churn rate is the ratio of revenue from users who stopped paying 
in the previous month to the revenue for a specific calendar month.
For example, Revenue Churn Rate (June) = Churned Revenue (June) / MRR (May).
*/
revenue_churn_rate AS (
SELECT 
    churned_rev.month,
    churned_rev.churned_revenue,
    LAG(monthly_mrr.mrr) OVER (ORDER BY churned_rev.month) AS prev_month_mrr,
    CASE 
        WHEN LAG(monthly_mrr.mrr) OVER (ORDER BY churned_rev.month) > 0 
        THEN ROUND(churned_rev.churned_revenue::DECIMAL / LAG(monthly_mrr.mrr) OVER (ORDER BY churned_rev.month), 2)
        ELSE NULL
    END AS revenue_churn_rate
FROM 
    churned_revenue AS churned_rev
JOIN 
    monthly_mrr ON churned_rev.month = monthly_mrr.month),
/*

Expansion MRR is the amount by which MRR has increased from one month to another.
It is calculated based on users who have started paying more in the current month.
 */
expansion_mrr AS (
SELECT 
    month,
    SUM(CASE 
          WHEN mrr > prev_mrr THEN mrr - prev_mrr ELSE 0 END) AS expansion_mrr
FROM (SELECT 
          user_id,
          month,
          SUM(revenue_amount_usd) AS mrr,
          LAG(SUM(revenue_amount_usd)) OVER (PARTITION BY user_id ORDER BY month) AS prev_mrr
      FROM 
          monthly_data
      GROUP BY 
          user_id, month) AS user_mrr
GROUP BY 
    month),
/*

Contraction MRR is the amount by which MRR has decreased from one month to another. 
It is calculated based on users who have paid less in the current month.
 */
contraction_mrr AS (
SELECT 
     month,
     SUM(CASE 
            WHEN mrr < prev_mrr THEN prev_mrr - mrr ELSE 0 END) AS contraction_mrr
FROM (SELECT 
         user_id,
         month,
         SUM(revenue_amount_usd) AS mrr,
         LAG(SUM(revenue_amount_usd)) OVER (PARTITION BY user_id ORDER BY month) AS prev_mrr
     FROM 
          monthly_data
     GROUP BY 
         user_id, month) AS user_mrr
GROUP BY 
     month
),
/*

Customer Lifetime (LT) is the average amount of time from the first payment to the churn of users. 
In other words, it is the total time the average user stays with the product.
 */
customer_lifetime AS (
SELECT 
     ROUND(AVG(lifetime_days), 2) AS avg_lifetime_days
FROM (SELECT 
          user_id,
          (MAX(payment_date) - MIN(payment_date))::INT AS lifetime_days
      FROM 
          project.games_payments
      GROUP BY 
          user_id
      HAVING 
          COUNT(payment_date) > 1) AS user_lifetime),
/*
Customer Lifetime Value (LTV) is the average total amount a single user spends over the entire time they use the product. 
In other words, it represents all the money that the average user pays to the company.
 */
customer_lifetime_value AS (
SELECT 
    ROUND(AVG(total_revenue), 2) AS avg_lifetime_value
FROM (SELECT 
          user_id,
          SUM(revenue_amount_usd) AS total_revenue
      FROM 
          project.games_payments
      GROUP BY 
          user_id) AS user_revenue)
-- Main query
SELECT 
    mmr.month,
    mmr.mrr,
    pu.paid_users,
    ar.arppu,
    np.new_paid_users,
    nm.new_mrr,
    cu.churned_user_count AS churned_users,
    cr.churn_rate,
    crv.churned_revenue,
    rcr.revenue_churn_rate,
    em.expansion_mrr,
    cm.contraction_mrr,
    cl.avg_lifetime_days AS customer_lifetime,
    clv.avg_lifetime_value AS customer_lifetime_value
FROM 
    monthly_mrr AS mmr
JOIN 
    paid_users_count AS pu ON mmr.month = pu.month
JOIN 
    arppu AS ar ON mmr.month = ar.month
JOIN 
    new_paid_users AS np ON mmr.month = np.month
JOIN 
    new_mrr AS nm ON mmr.month = nm.month
JOIN 
    churned_users AS cu ON mmr.month = cu.churned_month
JOIN 
    churn_rate AS cr ON mmr.month = cr.churned_month
JOIN 
    churned_revenue AS crv ON mmr.month = crv.month
JOIN 
    revenue_churn_rate AS rcr ON mmr.month = rcr.month
JOIN 
    expansion_mrr AS em ON mmr.month = em.month
JOIN 
    contraction_mrr AS cm ON mmr.month = cm.month,
customer_lifetime AS cl,
customer_lifetime_value AS clv
ORDER BY 
    mmr.month;
